// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJx5dw0Rc6HYJgm9DG6OkGBsiKwSDclMM',
    appId: '1:758581833811:web:6cfe401b9a6edbb20296a6',
    messagingSenderId: '758581833811',
    projectId: 'auteurly-5d03b',
    authDomain: 'auteurly-5d03b.firebaseapp.com',
    storageBucket: 'auteurly-5d03b.firebasestorage.app',
    measurementId: 'G-9X1LDVZVD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLtbFCqGqHjuMbPOzrVWuaapzdijAXRVI',
    appId: '1:758581833811:android:62ab41cd34a092560296a6',
    messagingSenderId: '758581833811',
    projectId: 'auteurly-5d03b',
    storageBucket: 'auteurly-5d03b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz9Y_2y_NJyaatkq243SzVtxmZ1T6d_aA',
    appId: '1:758581833811:ios:d68acd0e366466f50296a6',
    messagingSenderId: '758581833811',
    projectId: 'auteurly-5d03b',
    storageBucket: 'auteurly-5d03b.firebasestorage.app',
    androidClientId: '758581833811-manua972cam7u9men8qavt8n8fmj7srs.apps.googleusercontent.com',
    iosClientId: '758581833811-7797hhdm2nhh1vuc88fbp9h2su0aaqoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.auteurly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz9Y_2y_NJyaatkq243SzVtxmZ1T6d_aA',
    appId: '1:758581833811:ios:d68acd0e366466f50296a6',
    messagingSenderId: '758581833811',
    projectId: 'auteurly-5d03b',
    storageBucket: 'auteurly-5d03b.firebasestorage.app',
    androidClientId: '758581833811-manua972cam7u9men8qavt8n8fmj7srs.apps.googleusercontent.com',
    iosClientId: '758581833811-7797hhdm2nhh1vuc88fbp9h2su0aaqoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.auteurly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJx5dw0Rc6HYJgm9DG6OkGBsiKwSDclMM',
    appId: '1:758581833811:web:b8374e9d0d7c42c20296a6',
    messagingSenderId: '758581833811',
    projectId: 'auteurly-5d03b',
    authDomain: 'auteurly-5d03b.firebaseapp.com',
    storageBucket: 'auteurly-5d03b.firebasestorage.app',
    measurementId: 'G-8GFQ8ZVJYP',
  );
}
